name: Feature Request
description: Suggest a new idea or improvement
title: "[FEATURE] <brief description>"
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Help us understand your use case better by filling out the details below.

  - type: input
    id: motivation
    attributes:
      label: What's your use case?
      description: Why do you need this feature?

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the change or improvement you'd like to see

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other workarounds or tools you’ve tried?
